/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Tue Dec  3 11:42:42 2019. */

#include "ConfigMessage.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t xen_ConfigWrapper_fields[6] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, xen_ConfigWrapper, channelConfig, channelConfig, &xen_ChannelConfig_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, xen_ConfigWrapper, scale, channelConfig, &xen_Scale_fields),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, xen_ConfigWrapper, triggerTime, scale, 0),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, xen_ConfigWrapper, controllerConfig, triggerTime, &xen_ControllerConfig_fields),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, xen_ConfigWrapper, percussionChannelConfig, controllerConfig, &xen_PercussionChannelConfig_fields),
    PB_LAST_FIELD
};

const pb_field_t xen_ChannelConfig_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, xen_ChannelConfig, channelMapping, channelMapping, &xen_ChannelMapping_fields),
    PB_LAST_FIELD
};

const pb_field_t xen_ChannelMapping_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, xen_ChannelMapping, midiChannel, midiChannel, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, xen_ChannelMapping, cvChannelFrom, midiChannel, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, xen_ChannelMapping, cvChannelTo, cvChannelFrom, 0),
    PB_LAST_FIELD
};

const pb_field_t xen_ControllerConfig_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, xen_ControllerConfig, controllerMapping, controllerMapping, &xen_ControllerMapping_fields),
    PB_LAST_FIELD
};

const pb_field_t xen_ControllerMapping_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, xen_ControllerMapping, midiChannel, midiChannel, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, xen_ControllerMapping, midiController, midiChannel, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, xen_ControllerMapping, cvChannel, midiController, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, xen_ControllerMapping, cvBank, cvChannel, 0),
    PB_LAST_FIELD
};

const pb_field_t xen_PercussionChannelConfig_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, xen_PercussionChannelConfig, midiChannel, midiChannel, 0),
    PB_FIELD(  2, INT32   , REPEATED, STATIC  , OTHER, xen_PercussionChannelConfig, midiNotes, midiChannel, 0),
    PB_LAST_FIELD
};

const pb_field_t xen_Scale_fields[2] = {
    PB_FIELD(  1, INT32   , REPEATED, STATIC  , FIRST, xen_Scale, cents, cents, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(xen_ConfigWrapper, channelConfig) < 65536 && pb_membersize(xen_ConfigWrapper, scale) < 65536 && pb_membersize(xen_ConfigWrapper, controllerConfig) < 65536 && pb_membersize(xen_ConfigWrapper, percussionChannelConfig) < 65536 && pb_membersize(xen_ChannelConfig, channelMapping[0]) < 65536 && pb_membersize(xen_ControllerConfig, controllerMapping[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_xen_ConfigWrapper_xen_ChannelConfig_xen_ChannelMapping_xen_ControllerConfig_xen_ControllerMapping_xen_PercussionChannelConfig_xen_Scale)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(xen_ConfigWrapper, channelConfig) < 256 && pb_membersize(xen_ConfigWrapper, scale) < 256 && pb_membersize(xen_ConfigWrapper, controllerConfig) < 256 && pb_membersize(xen_ConfigWrapper, percussionChannelConfig) < 256 && pb_membersize(xen_ChannelConfig, channelMapping[0]) < 256 && pb_membersize(xen_ControllerConfig, controllerMapping[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_xen_ConfigWrapper_xen_ChannelConfig_xen_ChannelMapping_xen_ControllerConfig_xen_ControllerMapping_xen_PercussionChannelConfig_xen_Scale)
#endif


/* @@protoc_insertion_point(eof) */
