/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.4 at Sun Oct 27 09:09:10 2019. */

#ifndef PB_XEN_CONFIGMESSAGE_PB_H_INCLUDED
#define PB_XEN_CONFIGMESSAGE_PB_H_INCLUDED
#include "src/lib/nanopb/pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _xen_ChannelMapping {
    int32_t midiChannel;
    int32_t cvChannelFrom;
    int32_t cvChannelTo;
/* @@protoc_insertion_point(struct:xen_ChannelMapping) */
} xen_ChannelMapping;

typedef struct _xen_ChannelConfig {
    pb_size_t channelMapping_count;
    xen_ChannelMapping channelMapping[16];
/* @@protoc_insertion_point(struct:xen_ChannelConfig) */
} xen_ChannelConfig;

typedef struct _xen_ConfigWrapper {
    bool has_channelConfig;
    xen_ChannelConfig channelConfig;
/* @@protoc_insertion_point(struct:xen_ConfigWrapper) */
} xen_ConfigWrapper;

/* Default values for struct fields */

/* Initializer values for message structs */
#define xen_ChannelMapping_init_default          {0, 0, 0}
#define xen_ChannelConfig_init_default           {0, {xen_ChannelMapping_init_default, xen_ChannelMapping_init_default, xen_ChannelMapping_init_default, xen_ChannelMapping_init_default, xen_ChannelMapping_init_default, xen_ChannelMapping_init_default, xen_ChannelMapping_init_default, xen_ChannelMapping_init_default, xen_ChannelMapping_init_default, xen_ChannelMapping_init_default, xen_ChannelMapping_init_default, xen_ChannelMapping_init_default, xen_ChannelMapping_init_default, xen_ChannelMapping_init_default, xen_ChannelMapping_init_default, xen_ChannelMapping_init_default}}
#define xen_ConfigWrapper_init_default           {false, xen_ChannelConfig_init_default}
#define xen_ChannelMapping_init_zero             {0, 0, 0}
#define xen_ChannelConfig_init_zero              {0, {xen_ChannelMapping_init_zero, xen_ChannelMapping_init_zero, xen_ChannelMapping_init_zero, xen_ChannelMapping_init_zero, xen_ChannelMapping_init_zero, xen_ChannelMapping_init_zero, xen_ChannelMapping_init_zero, xen_ChannelMapping_init_zero, xen_ChannelMapping_init_zero, xen_ChannelMapping_init_zero, xen_ChannelMapping_init_zero, xen_ChannelMapping_init_zero, xen_ChannelMapping_init_zero, xen_ChannelMapping_init_zero, xen_ChannelMapping_init_zero, xen_ChannelMapping_init_zero}}
#define xen_ConfigWrapper_init_zero              {false, xen_ChannelConfig_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define xen_ChannelMapping_midiChannel_tag       1
#define xen_ChannelMapping_cvChannelFrom_tag     2
#define xen_ChannelMapping_cvChannelTo_tag       3
#define xen_ChannelConfig_channelMapping_tag     1
#define xen_ConfigWrapper_channelConfig_tag      1

/* Struct field encoding specification for nanopb */
extern const pb_field_t xen_ChannelMapping_fields[4];
extern const pb_field_t xen_ChannelConfig_fields[2];
extern const pb_field_t xen_ConfigWrapper_fields[2];

/* Maximum encoded size of messages (where known) */
#define xen_ChannelMapping_size                  33
#define xen_ChannelConfig_size                   560
#define xen_ConfigWrapper_size                   563

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CONFIGMESSAGE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
